export const FETCH_GENRES = 'FETCH_GENRES';
export const FETCH_BOOKS = 'FETCH_BOOKS';
export const FETCH_BOOK_COUNT = 'FETCH_BOOK_COUNT';
export const FETCH_LOADING_STATUS = 'FETCH_LOADING_STATUS';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const SET_BOOK_QUANTITY = 'SET_BOOK_QUANTITY';